image: circleci/golang:1.12-node

stages:
  - test
  - build
  - release

lint:
  stage: test
  script:
    - make check-style
  
tests:
  stage: test
  script:
    - make test

release:
  stage: release
  script:
    - make
    - cd webcomponent && npm run build
  only:
    - tags
  artifacts:
    paths:
      - dist/*.tar.gz
      - webcomponent/dist/matternelle.js
